### ISSUE TITLE
Link to setting page on https://docs.fiberplane.com/docs is broken/doesn't work.

### ISSUE THREAD

**Issue by gaurab-khanal** [fiberplane/docs#16]
![image](https://user-images.githubusercontent.com/40165867/221602595-f0522120-b322-4051-b22a-46e04ec4bb49.png)

**Comment by gaurab-khanal** [comment]
I want to work on this issue. Please assign me this issue. I am new here and participating in open source challenge.

**Comment by shashank-mishra14** [comment]
Hey, seems like it can be resolved, assign it to me.
